INSERT INTO PROFESSOR (NOME, EMAIL, SENHA, DATA_NASC) VALUES ('root', 'root@root', 'root', '01-01-0001');
INSERT INTO DISCIPLINA(NOME) VALUES ('Banco de dados');
INSERT INTO TURMA(COD, SEMESTRE, PROF_COD, DISC_COD) VALUES (1, '20191', 1, 1);